name: pinata_cloud_sdk
description: >
  A Dart SDK for interacting with Pinata Cloud. 
  Supports uploading files and creating signed upload URLs to IPFS.
version: 0.0.1
homepage: https://github.com/romavicdosanjos/pinata_cloud_sdk
repository: https://github.com/romavicdosanjos/pinata_cloud_sdk
issue_tracker: https://github.com/romavicdosanjos/pinata_cloud_sdk/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# No assets or fonts used yet
